// ==UserScript==
// @name         E-Hentai Galleries
// @namespace    https://github.com/msthoshi/UserScript
// @version      2025-12-14T00:27:00
// @description  E-Hentai Galleries
// @author       Yuyushiki
// @homepageURL  https://github.com/msthoshi/UserScript
// @supportURL   https://github.com/msthoshi/UserScript
// @updateURL    https://github.com/msthoshi/UserScript/raw/main/E-Hentai_Galleries.user.js
// @downloadURL  https://github.com/msthoshi/UserScript/raw/main/E-Hentai_Galleries.user.js
// @match        https://e-hentai.org/
// @match        https://e-hentai.org/?f_*
// @match        https://e-hentai.org/g/*/*/
// @match        https://e-hentai.org/g/*/*/?p=*
// @match        https://e-hentai.org/s/*/*
// @icon         https://e-hentai.org/favicon.ico
// @grant        none
// ==/UserScript==

if ((/^https?:\/\/e-hentai\.org\/(?:\?f_.+)?$/).test(document.URL)){
    RunYuyushiki = function (){
        var elements, element, arrtitle, regtitle;

        arrtitle = [
            '#\\d\\d-(?:0[1-9]|1[012])-(?:0[1-9]|[12]\\d|3[01])｜Miyuka',
            '810034', //Noi
            '1697123', //akiba
            '1989974', //Rひつじ
            '2924833', //コタコタ
            '2987812', //愛猫
            '3193946', //zzzzz
            '3218096', //tt
            '4622167', //akaneko
            '5045551', //フヤ
            '5437476', //遼来来
            '5806554', //NTRの村
            '6152589', //絶え間なく注ぐAIの名を
            '6580587', //トエ
            '8976533', //en
            '9210862', //ゴリゴ
            '11261350', //Koni
            '38077983', //ドラムカン
            '38990082', //Takoro
            '42961512', //9527
            '51177408', //神社
            '70822129', //mi
            '79152651', //Gizen
            '82986155', //rivet
            '83370956', //AS
            '91609891', //JJ
            '91841855', //kanon
            '92279776', //Stella
            '93228633', //犬
            '101284864', //myuto
            '103109616', //緊縛執行者
            '106119305', //シンクレア
            '102284126', //25℃
            '102860563', //yom
            '103093128', //ココ
            '104049240', //Ahoge @Rua你呆毛
            '104427100', //Ayano
            '104741026', //Azz
            '107739483', //あき
            '108858033', //可哀想じゃなきゃXXX
            '109552994', //エロ草
            '109914031', //nero
            '109983791', //METEOR
            '113736534', //ダークネス
            '115558864', //るいり
            '115698769', //ぴょん
            '119846491', //yumekui
            '121043961', //haruto
            '137773217', //asastte
            '10taclex10tacle',
            '18anime_18',
            '18animegirls',
            '1ThemainMan1',
            '2_shark',
            '31245346|103148575',
            '3other 3ature|118244047',
            'A room where a married woman smells|人妻が薫る部屋',
            'a0iisa|A0IISA',
            'abogadoman|あぼがどマン|119064539',
            'AbramovAI|117582837',
            'Abscord_Orvus',
            'Ace火神',
            'action-star',
            'Adam Eva',
            'Adeline/艾德琳',
            '^adnis |\\[adnis\\]',
            'AELLOW',
            'AHY2',
            'Ai Art_Dreamer',
            'Ai Boy',
            'AI Angelina Jolie',
            'AI Anna Kendrick',
            'Ai Beauty art c',
            'AI Chloe Grace Moretz',
            'AI DOG',
            'AI DRAW \\(長信\\)',
            'AI Freya Allan',
            'AI Frontier Rev',
            'AI Gigantic Girl',
            'AI GirlLove',
            'AI Jodie Foster',
            'AI KOR',
            'AI Mckenna Grace',
            'AI Natalie Portman',
            'Ai Porn Work',
            'AI Rachel McAdams',
            'AI Sydney Sweeney',
            'AI_DaYiMa',
            'Ai_emikoo',
            'AI_Omaga',
            'AI-TAKASHI-YA',
            'AI\'s Neko',
            'AIAIZone',
            'AiASAG',
            'AIBOOBY',
            'AIBUNNY|AIBunny',
            'AICG',
            'AIconsomme',
            'AID[ _]oll',
            'AIde\\(エイド\\)',
            'aieditor',
            'aiEgg',
            'AiFantasy',
            'A[Ii]Fish[Bb]all',
            'aijuicer',
            'AImalin|美少女がキモ男に妊娠させられる',
            'Aindroid',
            'Ainme',
            'AIPotions',
            'Airubyrem',
            'AIShowMe',
            'AIStudio',
            'AItono',
            'AIusagichan',
            'AIWaifuClub',
            'A[Ii]WaifuDXD',
            'AIypse|10485395',
            'AI小松鸟',
            'Akatsuki Ichika World',
            '[Aa]ksn',
            ' Arisua - ',
            'Allenby',
            'AlwaysOlder',
            'Amakawa is reflecting',
            'AmeSketch',
            'AndestanVita042|117458084',
            'Anh Dang',
            'Anilvl',
            'Animated Perfection AI',
            'AnimeParadise',
            'ANIMMORTAL',
            'Anipai|ANIPAI',
            'Ankake Nameko|餡掛けなめこ',
            'Anor Londo',
            'Anto-kun',
            'aPAPER|^apaper\\)',
            'araaiart',
            'ARD [\\s\\S]+ \\(Patreon\\)|\\[ARD\\]',
            'ArfX',
            'ARIGA',
            'ArimaAgamiAI',
            'Arinena|31012180',
            'ARKETSUAI|ArketsuAI',
            'ArlanMi',
            'Artifical Art',
            'artist- Sano_AI',
            'artkoikoi',
            'artriako',
            '(?:asa|あさ)_034',
            'asastte|138085154',
            'ASDFG-did-lover',
            'Asphyxia',
            'atorieHJ',
            'ATYPO',
            'Aurora_S2',
            'Axiah',
            'Ayaaaaa|91528372',
            'ayxgirl|Ayx Girl',
            'Azusa_Yui',
            'AzzAI',
            'BaldSensei',
            'Balecxi',
            'BanAi',
            '^Banshou - |\\[Banshou\\]',
            'Bartoon',
            'BBoing',
            'BBstaff|BBStaff',
            'Benj17',
            'BGM ∞',
            'bianT',
            'BigMelons',
            'Bigornox',
            '^Bishop - |\\[Bishop\\]',
            'Black Miracle',
            'BlackedNeeko',
            'Blavker|13881681',
            'bleachmama',
            'Bleep',
            'Bloobill',
            'Blue Forest',
            'BlueBird',
            'bluffman',
            'Bluu AI',
            'BMS07',
            'bompcat②|118061342',
            'Bonyunbonyun Heaven',
            'Boobacious',
            'Boryuka',
            'BoxDay AI',
            'breadman|58131017',
            'BribristleBowie',
            'Brynn',
            'BubbleTeeXL',
            'ButterStudio',
            'ByTheBroken1',
            'Ca_Mel',
            'CatalystAI',
            'CCCraftA[Ii]|CC Craft A[Ii]',
            'Chickenbeautiful',
            'chiko_',
            'Chocopizza|ChocoPizza',
            'chongsheng|110608626',
            'ChurnVeil',
            'Cidrex',
            'circle_ueponzu',
            '[Cc]ivit[Aa][Ii]',
            'cl-_-lo',
            'Clothes AI',
            'CMFHF',
            'cMonster',
            'CodeMistake',
            'Coiefen',
            'Coldenic',
            'Comboappofrice',
            'CometAzur',
            'Coolsummer',
            'corntoss',
            'Cottonmilk',
            '^Crank',
            'Creamy AI',
            'CryxAI',
            'cugp5343|114480180',
            'Custom Firingu X',
            'CunnyFunky',
            'Cyb3rD3votion',
            'Cyber-Wifu',
            'CZYH',
            'Dacchuno',
            '[Dd]aidouji(?:PV|pv)',
            'DarkFallenAngel',
            'Dartzai',
            'DavionCoreArt',
            'DazzleVwj',
            'Ded_173',
            'DeepMole',
            'Deik0',
            '^[Dd]espair |\\[despair\\]',
            'Dexter|德叔',
            'DiaseePauwel',
            'Digital Waifu Gallery',
            'Dino@Top|41090148',
            'DioH123',
            'Ditto Seeker',
            'DJ Su',
            'DreamcoreArt',
            'DomSweMale',
            'Donbe',
            'Dots',
            'DozyMoth',
            'Dreamyan',
            'Dreiko',
            'dreson',
            'drücken|8083859',
            'Dsd Adw',
            'Duderu',
            'Duxvector',
            'East Tom|119237488',
            'Ecchi Eden',
            '^Eden ',
            'edosynf',
            'edsa2004',
            'Ein_REBOOT',
            'EKYNOXE',
            'ElfOlive',
            'Elincia_BE',
            'Elkazama_Yumi',
            'Emi Doodlez',
            '^Enaki - |\\[Enaki\\]',
            'ERION',
            'EroartAI',
            'Ero[Mm]omo [\\s\\S]+ \\(Patreon\\)|\\[Ero[Mm]omo\\]',
            'Ero[Pp]hoenix Studios',
            'EroSketch',
            'ErslAIt',
            'Erutoria',
            'Eterno(?:AI|ai|Ai)',
            'Ethical Muse',
            'ETUSiAi',
            'euskyart',
            'Ezbreeze',
            'EZNTR',
            'FADE',
            'Falpiva|91046770',
            'fatFlyingSheep3|105189373',
            'flax_AI',
            'Floox508',
            'Flowersbeautiful',
            'formalaut7699',
            'Forplay',
            'foursama|5907510',
            'fr34ky5',
            'Freadeeb_TnT',
            'FRSH_Pel0v',
            'FryTime',
            'FunnyBunny',
            'Futagenn',
            'Fuyara',
            'FuyuBloom',
            'F天青',
            'Gb_5|92491138',
            'Generic_senpAI',
            'GenkiAi',
            'Genova pixiv',
            'Geo[ \\-]san',
            'Geroin ya',
            'Gettan',
            'GikoKitune',
            'Ginto(?:AI|ai)',
            'GizGizmGimo',
            'GN320',
            'Gofenix/Dragonicxs',
            'Gog0chan',
            'Good Morning-sama',
            'GORILLAFROG',
            'Gragas743|gragas743',
            'GreekoAI',
            'GREENHEART',
            'GVUKUB|gvukub|Gvukub',
            'H Jam',
            '[Hh]ajily',
            'HalfLove',
            'Hammiai',
            'haniodon',
            'harajiro_butakimchi',
            'Heaven RB',
            'Hell[Tt]o[Yy]ou',
            'Hentai Hideout',
            'HentAI_Rtist',
            'hero60',
            'Hessen_52hz',
            'HikaruAI',
            'hirosaTochisato',
            'HiStoryIa',
            'Hoeeeng',
            'H[Oo][Gg]s905|42172340',
            '^holic ',
            'HoloAI',
            'HONGCHA',
            '^Honokaa ',
            'Hot Finger Pepper',
            'hougyou',
            'Howsir',
            'hstorytaimu',
            'huanai',
            'Hurry-Workshop/Anivoice',
            'IceZ|109454860',
            'ieh002',
            'IGarum|11920967',
            'ill20934',
            'illyFurina',
            '[Ii]lulu[Ll]over',
            'ImperfectionAI',
            'InferAI',
            '^inn ',
            'intwai',
            'IronAIArt',
            'Isterya',
            'ItzzMendo',
            'IWD AI',
            'Jackchief',
            'JAPAIN|じゃぺいん',
            'JazkE',
            'jerry1805',
            'JessicaRae',
            'JessieAI',
            'Jinnnn',
            'JJNKAI',
            'JoeinPixels',
            'Jonn Cinabonn Jovi',
            'jormunAi',
            'Jukujo Kami no Kuroana|熟女神の黒穴',
            'jull123',
            'Juucyai',
            'Kairo Art',
            'Kaiysx',
            'KALA AI NSFW',
            'KalistaFunz',
            'KanamiEcchi',
            'Kangaroo [\\s\\S]+ \\(Patreon\\)|カンガルー/ Kangaroo',
            'kanon648',
            'karmarks',
            'KatKirara',
            'KawaGawa|117534671',
            'keoly',
            'Khris AI',
            'Kichiku-Sensei',
            'Kinzuia_chan',
            'Kisara146',
            'KisenAI',
            'KKKBBB|102726831',
            'KM KingMaster|KM \\| KingMaster',
            'Koa-san',
            'Kobenibeni \\| Waifus',
            '^koharu\\)',
            'koikatsufans',
            'Koina(?:Art|ART)',
            'Koki Art',
            'kokoyone|102034245',
            'Kord A[Ii]',
            'Koryax',
            'KourageGTS',
            'KrebAI',
            'Kris_S',
            'Kuporosso',
            'Kxin2233',
            'Kyoko\'s Kingdom|きょこーの王国',
            'Kyonkanie',
            'Laino Airt',
            'Lam Vex',
            'LAMON',
            'langust022',
            'lappyoru',
            'lattekoi5252|86973404',
            'LaughingFoxComics',
            'LewdCreationAI',
            'Lewder',
            'Lewdiii',
            'Lewdink',
            'LewdLilith',
            'lewisaiart',
            'Libesan2',
            'LigmaSugmadi',
            'Lile\\/リール',
            'LimbusCompany',
            'Liname',
            'Live[Ff]rog|FrogAI',
            'LK_JEWELS',
            'Lord of Waifus',
            'Lori33',
            'LotteryFate',
            'Love Diffusion',
            'Love4UAndAI',
            'Lovehuwu|LoveHUwU',
            'LovelyZen',
            'LowFireStudios',
            '[Ll]ovenight',
            'LSP集合所',
            'Luka45',
            'LunAra',
            'LustBild',
            'Lusty ?Nymphi',
            'LuxaArtdios',
            'luzy2525',
            'Ly117',
            'm6jik6',
            'MacArooN',
            'Machina Ai',
            'Magiskuwa',
            'maiQOS',
            'Märchen',
            'markinson|106442227',
            'MarnieAI',
            'MarnieDark',
            'Matcha Muse',
            'Mater-K',
            'Matthew',
            'MaxMusclerlc',
            'may_rain',
            'Meitabuu',
            'Melocotón|107679485',
            'Meowu laha',
            'MessingwithAI',
            'Mesubutagoya|雌豚小屋',
            'Meteor (?:0[1-9]|1[012])\\.(?:0[1-9]|[12]\\d|3[01]) ',
            'Mia Milanová',
            'Miah2d',
            'midmimicry',
            'Mika157/Bunnynavia',
            'Mikayori',
            'Mikitoon_studio',
            '^miko ',
            'Miku\’s AI',
            'Milf_kun',
            'milfanimee',
            'minakaze',
            'ming shen',
            'mipjeas',
            'Miroro',
            'MirrorArtIA',
            'MikasakaBoka/BokaChan',
            'MisterAsura',
            'MKyBUSH',
            'mmkk|107330927',
            '^MML ',
            'MMLOVE|91707537',
            'mnemosynekoto|Mnemosynekoto',
            'mochimochiya',
            'Modeus14',
            'Mofulyen',
            '[Mm]ogu-[Tt]yan',
            'MohumoAi',
            'Moke P@treon',
            'MOKIIIMOKIII',
            'Momoyashiki Akari',
            'Moon Petal',
            'Moriaaa',
            'MountCre',
            'mpena24',
            'Mr(\\. )?Teardrop',
            'Mugi \\| むぎ',
            'Murata_san_FANBOX',
            'Myanu',
            'MylieAI',
            'Nakanaka [Nn]ana',
            'Nakatori',
            'NAKS',
            'Nameless King',
            'Namira',
            '^Nanami - |\\[Nanami\\]',
            '[Nn]ankoai',
            'Nasty|18386645',
            'NatsuYoru',
            'Necromancer893',
            'nekmio_ui|104464504',
            'neko_menber',
            'Nekohouse ID',
            'neko-kuro',
            'nelshot',
            'Neroshiboshi',
            'neruton',
            'Netorare-san',
            'Neural Nymphs',
            'NewVegas',
            'niauno|16691530',
            'Nixny',
            'NnnN_Generator',
            'NO ONE pixiv',
            'Noffa',
            'NONOSAN',
            'Noonq',
            'NosferartIA',
            'not hen',
            'NSFW Art137',
            'NSFWreigan',
            'NSN Studio',
            'NTR HX',
            'NTRCookie',
            'ntrzelda',
            'Nurennuren|ヌレンヌレン',
            '[Nn]yx[Ww]orks',
            'OBEY|1730820',
            'Ogurifo',
            'Oh_yuae',
            'OIGrizzle',
            'Oishi Okaze',
            'Okazai Art',
            '[Oo]niha- |^[Oo]niha - |\\[[Oo]niha\\]',
            'ooqwqqaq',
            'OpisVore',
            'OppaiGirls',
            'OrangeO|orangeo',
            'OrionAI',
            'osanpomichi',
            'osu tarou\\(yamaguti maso\\)|オス太郎\\(山口マソ\\)',
            'Otonashi Ai',
            'Panic [Aa]merica',
            'pantyless',
            'Paperhero',
            'Parmee',
            'Perorobin|52117493',
            'Pheus',
            'PICPONG',
            'PipiDoge',
            'PIPITUA',
            'Pirate Wind Cat',
            'PISANTO皮三豆',
            'PixelNinjaArt',
            'pixel_overdose',
            'Poggerrogger',
            'pokemon e love',
            '^pomo ',
            'Ponponmaru',
            'Pre-Factory',
            'PriestOfArt',
            'Primo Sensei',
            'ProGenArts',
            'prompt filters bypass',
            'Ps-ai|PS-AI',
            'PsyopsAI',
            'PureTone|109612846',
            'Purisima',
            'Purpleh31',
            'QAQ2\\.0|102102635',
            'qos警告',
            'qqqpppqpqp整合',
            '^Ragnarock - |\\[Ragnarock\\]',
            'Rahmat',
            '[Rr]aiden190',
            'Ramen-chan',
            'RandoAI',
            'Rankabee',
            'ranzed|17818148',
            'Rasha125',
            'RazorThreat',
            'Realistic AI(?: animation)? works',
            'RebornMe|84002642',
            'RecSefer/Sigabelle',
            'red desire',
            'RedCherryArt',
            'Redilus',
            'REENKA25|reenka25',
            'regy_2|120291703',
            '^rei ',
            'ReiNa',
            'Remux',
            'ReverendGreatLove',
            'Revy Neon',
            'riko_77|118090769',
            'Rin_String',
            'RinkoRen',
            'Rino-mii_Noa',
            '^RockMan - ',
            'rose_rune',
            'Rqxy|6156788',
            'RUIMA',
            'RUKA@NTRに身を焦がし者',
            'Rule34(?:Lab| Diffusion)',
            'Ryan4s\\(93340616\\)',
            'sabertooth|SabertoothAI',
            'SACRA|111085245',
            'saiminai',
            'Saint Mary',
            'Samnite II',
            'SAMSARA_AI',
            '^SANARIA [\\s\\S]+ \\(Patreon\\)',
            'sasuga_yukke',
            'SatoAI',
            'SAWAHEBI 蛇',
            '^Sayaka [\\s\\S]+ \\(Patreon\\)|\\[Sayaka\\]',
            'Sbookner',
            'Sbwaifus',
            'Scallion flavor|92527277',
            'Scarlet_Meow',
            'Scriptorium',
            'SecreArt',
            'SEN-HWA',
            'Sephiaton',
            '^Setsuna - |\\[Setsuna\\]',
            'Sgrodolo',
            'ShadowJB',
            'Sharinel',
            'Sheldon NTR',
            'Shexyo',
            'Shigure cafe|時雨カフェ',
            'Shinimono|しにもの',
            'Shione\'s works',
            'shippaiyasan|失敗屋さん',
            '^Sira ',
            'Shirobako88',
            'SilentPalette|120198490',
            'SilentWarrior',
            'Silvesta',
            'Sinity',
            'SInNA',
            'sirokata|しろかた',
            'Sixsix201',
            'SK_Anime\\/SKK',
            'Sketiku',
            'SkyPassion',
            'SlimyGalsy',
            'SlutCentralAI',
            'Smol NTR',
            'SnowBunnyWaifus',
            'Snowlax',
            'Sodalord',
            'SoL22',
            'solomon10',
            '[Ss]overeign',
            'Spairk1313',
            'SpasiboAI',
            'spe-than',
            'Squeeshy',
            'Stable Reality',
            'StarcreamsGhost',
            'Starsay',
            'StarSigilArt',
            'StasisBBC',
            '[Ss]tefan',
            'stella (?:- |)\\[NSFW\\]',
            'Stigmata',
            'STKyrie',
            '^Stormy',
            'StrayRevy',
            'Strelitzia',
            'stuffedpepper',
            'subcharalove',
            '[Ss]ub [Kk]ing',
            'SukiyakiNeko',
            'SultrySpark',
            'syafu_AI',
            's\\.h\\.t|11751692',
            'ta457',
            'tabakowayame',
            'Tamagochiiii',
            'Taroberry',
            '^tarte - |\\[tarte\\]',
            'Taugust',
            '^tenk ',
            'terta|526122',
            'terusa [\\s\\S]+ \\(Patreon\\)',
            'The Milk Man',
            'Thebardspirit',
            'TheFarAi',
            'TheHypno7ist',
            'TheMaker___',
            'Tiger87|タイガー87',
            'Tillian',
            'TipperGoreWasRight',
            'Tkz\\(116616648\\)',
            'Tommu',
            'tonkotsu_soup|Tonkotsu Soup',
            '^Toratora |\\[Toratora\\]',
            'TorogaoUni',
            'Toromiya|とろみ屋',
            'TrogiAi',
            'TsarAi',
            'TSM2330',
            'Tsubaki [\\s\\S]+ \\(Patreon\\)',
            'Tsukinoo',
            'TTAKO',
            'Twisted Ideas Studio',
            'UCHI AI Art',
            'UCHIAI',
            'ufiaw',
            'Unbuttoned Innocence',
            'Undresser',
            'Unknown - (?:\\(RE\\)|\\(Reuploaded\\) )?NTR',
            '[Uu]nifans',
            'UnityNay',
            'UnjobDespiert',
            '^unreal ',
            'URDha|14225123',
            'usaocha',
            'userzon',
            'UWAH',
            'Vanitas_AI',
            'VantaWaifu|VANTAWAIFU',
            'Velurieve',
            'VelvetDesires',
            'VertiloAI',
            'Virijir720',
            'VirusB90',
            'VoidMen',
            'Vrty',
            'VvtD',
            'Yamche',
            'Yoruneko',
            'YukinoArt',
            'YumiKoi',
            'YuttaKarii',
            'Wagamama\\!\\!\\!',
            'Waifu Perfection AI',
            'Waifu_universe_77',
            'WaifuArchitect',
            'WaifuInvoker',
            'WaifuLover',
            'Wamia12',
            'Wang Tarik|62436170',
            'Wardens',
            'WarOfFree98',
            'warofree',
            'weeb2weeb',
            'WhiteSnow211',
            'WienerGens',
            'Wingzy',
            'Wisdom Seeker',
            'woshould',
            'Wumi',
            'wwwww2',
            'x[Dd]omi[Kk]ami',
            'xdwft2',
            'Xerganea|90281477',
            'XHome',
            'xOppAIsensei',
            'xyxonrh',
            'yagaminomori|ヤガミノ杜|\\(emiya\\)',
            'YakeArt',
            'yanai_hide',
            'YashugAI',
            'Yeeting',
            'YKHADES2333',
            'Yokuto',
            'Yoru akubi shōtai|夜あくび小隊',
            'YORU NEKO|YoruNeko',
            '(?:^| )yoshi ',
            'YuinaJoy',
            '^Yukina |Yukina [\\s\\S]+ \\(Patreon\\)',
            'Yukino A[Ii]',
            '^yuyu ',
            'yygg',
            'zaidxxxart',
            'Zcqrlet',
            'Zen3',
            'Zenit2cai',
            'zipzip|Zipzip',
            'zurizuri|110996891',
            '\\[11_22\\]',
            '\\[aHero\\]',
            '\\[AIbro\\]',
            '\\[AIlya\\]',
            '\\[Akihime\\]',
            '\\[Bell\\]',
            '\\[[bB]onno\\]',
            '\\[chack\\]',
            '\\[coqiaku\\]',
            '\\[Daisy\\]',
            '\\[Darkmagic\\]',
            '\\[Ein\\]',
            '\\[ETUS\\]',
            '\\[Feather\\]',
            '\\[Floox\\]',
            '\\[Fraia\\]',
            '\\[Fun\\]',
            '\\[furi\\]',
            '\\[Girlstar\\]',
            '\\[Gizen\\]',
            '\\[Gorgonzola\\]',
            '\\[[Gg]ray\\]',
            '\\[Hannya\\]',
            '\\[Himeno\\]',
            '\\[hunny\\]',
            '\\[HYC\\]',
            '\\[ishida\\]',
            '\\[Kanuck\\]',
            '\\[Komachan\\]',
            '\\[(?:Komagome|こまごめピペット)\\]',
            '\\[Lucy\\]',
            '\\[man hu\\]',
            '\\[ManAI\\]',
            '\\[Maple\\]',
            '\\[[Mm]azo [Bb]uta\\]',
            '\\[(?:Milk Paradise|みるくパラダイス)\\]',
            '\\[minakaze\\]',
            '\\[miyabi\\]',
            '\\[Miyu\\]',
            '\\[Meow\\]',
            '\\[myuto\\]',
            '\\[Naks\\]',
            '\\[Nayami\\]',
            '\\[NONOSAN\\]',
            '\\[noroj\\]',
            '\\[NT00 Fans\' Fan-Created Works\\]',
            '\\[Nyc3e\\]',
            '\\[Okreet\\]',
            '\\[Orange\\]',
            '\\[OTA\\]',
            '\\[POGO\\]',
            '\\[Potions\\]',
            '\\[PS-AI\\]',
            '\\[rara\\]',
            '\\[Remon\\]',
            '\\[Ryx\\]',
            '\\[Sion\\]',
            '\\[Sukesuke\\]',
            '\\[Sulfur\\]',
            '\\[tamagoyaki\\]',
            '\\[Tamayuki\\]',
            '\\[white album\\]',
            '\\[yang\\]',
            '\\[Yuuna❤️?\\]',
            '\\[Zuki\\]',
            '\\[えーあい\\]',
            '\\[エロエロ天国\\]',
            '\\[タカーノ\\]',
            '\\[ドゥドゥ\\]',
            '\\[ぱにぱに\\]',
            '\\[ベロナス\\]',
            '\\[みれ\\]',
            '\\[红姬\\]',
            '\\[限界\\]',
            '\\[贱兔\\]',
            '\\[奶孑\\]',
            '\\[生たまご\\]',
            '\\[세로냥\\]',
            '\\([Aa]lbatross\\)',
            '\\(HentaiLove\\)',
            '\\(MULLON\\)',
            '\\(Nanami\\)',
            '\\(Patreon\\) Chizuru - ',
            '\\(Sylveria\\)',
            '\\(week2343\\)',
            '\\(紫月\\)',
            '【AI自制】',
            '【peng】',
            '【にっか】',
            'あいぶんめい|113642305',
            'アガツマミノル|109662215',
            'あくああい',
            'あちちハウス',
            'あま原屋',
            'ウララ先生',
            'えむすたでぃお',
            'エロエロ研究会',
            'お姉さん 【(?:GOLD|SILVER)】',
            '^かーむ ',
            'かたい棒 Hard Stick',
            'からーげ',
            'キウイ/Kiwi',
            'ゴールシックス',
            'こまごめピペット',
            'サークル休館日',
            'サークル童貞ペンギン',
            'ジアノトーア',
            'シコリの森',
            'じゃがいもホクホク北海道',
            'スクールパラダイス',
            'ステーキくん',
            'ズリ公くん|2614854',
            'だぶるクリっく',
            'だまご屋',
            'たむら/Tamura',
            'ななしこ',
            'ニャンコサキ',
            'ニンニクましお',
            'ぬきのすけ',
            'ねとれや',
            'パニックアメリカ',
            'パパ活バズーカ',
            'ひゅたたたたた',
            'マニアック太郎',
            'マルテンサイト変態|5738149',
            'みー@AIイラスト',
            'みやもりちゃん\\(Miyamori\\)',
            'みるふあい',
            'めろんアイスちゃん寝る',
            'モルモル倶楽部',
            '^ヤマタロー ',
            'ラブリークラフト',
            'わさびまぐろ',
            '愛燈tv_official',
            '阿古りむ|AKoRimu Art',
            '安托哦_Antuoo|41145678',
            '雨柳アトラ / Atra|9791149',
            '犬ポテト',
            '犬魔人',
            '淫乱マッスル',
            '梅洞てんぷりゃー',
            '絵師たか',
            '大トロ定食\\(otoro\\)',
            '革命再继续|115264667',
            '悲しいサイ',
            '雷門AIショップ',
            '黄色固体胶（zzzzz',
            '鬼畜小次郎',
            '鬼くるみ',
            '鬼见愁',
            '巨乳加大分',
            '空小孩化',
            '狗百代',
            '狗飯D|65800736',
            '幻想支線\\|愛と夢物語',
            '小涩猫猫Nekolock \\(108435514\\)',
            '小莉|15406718',
            '少把盐|91270513',
            '黒猫の隠れ家',
            '墨迹',
            '黒糖サムライ',
            '咕哒guda',
            '菜鸡喵',
            '鮫島猛',
            '零の旅人',
            '紫微星|1754968',
            '上官飞云|92168008',
            '私立 ななつ星中',
            '重铸18\\+荣光',
            '神圣之杯|98427552',
            '外出し失敗',
            '大雷显圣真君',
            '田边重工',
            '他力本願寺',
            '羞恥工房',
            '兆楠 湯',
            '逐辰十七|57731832',
            '泽拉图',
            '天空之上|51354050',
            '名無しのあに◯ん民',
            '成田大进|53214500',
            '日曜日のままま',
            '排便量管理人\\(aya\\)',
            '八可可Barcoco',
            '风萤月|116577275',
            '忘崽牛奶|103900587',
            '右向カレイ|86707199',
            '無糖ノ夜|41564466',
            '模因moyin',
            '山口雄太郎',
            '暗鸦c|13711016',
            '勇者のパシリ＠AI',
            '油炸小肥龙',
            '夜あくび小隊',
            '落花入梦',
            '龍山 T-YAMA|215154',
            '玲菜|68382480',
            '咔嗒咔嗒|67919044',
            '侘び寂び。|115866675',
            '悪い果|104257480',
            '龙蛇仙|104935838',
            '丶黑谷雨泽',
            '[Ff]utanari',
            '[Cc]ollection'
        ]
        regtitle = RegExp(arrtitle.join('|'));

        elements = document.querySelectorAll('table.itg.glte > tbody > tr');
        for (element of elements){
            if (regtitle.test(element.querySelector('div.glink').innerText)){
                element.style.display = 'none';
            }
        }
    }
    popUp = function (URL, w, h){
        var arrMatch, element;
        arrMatch = URL.match(/gid=(\d+)&t=/);
        if (arrMatch){
            element = document.getElementById('posted_' + arrMatch[1]);
            if (element){
                navigator.clipboard.writeText(element.innerHTML);
            }
        }
        return(false);
    }
} else if ((/^https?:\/\/e-hentai\.org\/g\/\d+\/[0-9a-f]+\/(?:\?p=\d+)?$/).test(document.URL)){
    (function() {
        var element, strH;
        element = document.querySelector('div.gm');
        strH = '20px';
        function ClickElement(){
            if (element.style.overflow == 'hidden'){
                element.style.height = 'auto';
                element.style.overflow = 'visible';
            } else {
                element.style.height = strH;
                element.style.overflow = 'hidden';
            }
        }
        element.style.height = strH;
        element.style.overflow = 'hidden';
        element.addEventListener('click', ClickElement, false);
    })();
} else if ((/^https?:\/\/e-hentai\.org\/s\/[0-9a-f]+\/\d+-\d+(?:\?nl=\d+-\d+)?$/).test(document.URL)){
    (function() {
        var strURL, arrMatch, strFileName;
        function PasteFileName(){
            navigator.clipboard.writeText(strFileName);
        }
        strURL = document.URL;
        arrMatch = strURL.replace(/\?[\s\S]+$/, '').match(/(\d+)-(\d+)$/);
        if (arrMatch){
            strFileName = arrMatch[1] + '-' + ('0000' + arrMatch[2]).slice(document.querySelector('#i2 > div.sn > div > span:nth-child(2)').innerHTML.length * -1);
            document.querySelector("#img").addEventListener('contextmenu', PasteFileName, false);
            document.querySelector("#i6").addEventListener('contextmenu', PasteFileName, false);
        }
    })();
}
