// ==UserScript==
// @name         E-Hentai Galleries
// @namespace    https://github.com/msthoshi/UserScript
// @version      2025-12-09T20:56:00
// @description  E-Hentai Galleries
// @author       Yuyushiki
// @homepageURL  https://github.com/msthoshi/UserScript
// @supportURL   https://github.com/msthoshi/UserScript
// @updateURL    https://github.com/msthoshi/UserScript/raw/main/E-Hentai_Galleries.user.js
// @downloadURL  https://github.com/msthoshi/UserScript/raw/main/E-Hentai_Galleries.user.js
// @match        https://e-hentai.org/
// @match        https://e-hentai.org/?f_*
// @match        https://e-hentai.org/g/*/*/
// @match        https://e-hentai.org/g/*/*/?p=*
// @match        https://e-hentai.org/s/*/*
// @icon         https://e-hentai.org/favicon.ico
// @grant        none
// ==/UserScript==

if ((/^https?:\/\/e-hentai\.org\/(?:\?f_.+)?$/).test(document.URL)){
    RunYuyushiki = function (){
        var elements, element, arrtitle, regtitle;

        arrtitle = [
            '1697123', //akiba
            '8976533', //en
            '42961512', //9527
            '103109616', //緊縛執行者
            '106119305', //シンクレア
            '102284126', //25℃
            '109552994', //エロ草
            '115558864', //るいり
            '115698769', //ぴょん
            '18animegirls',
            '3other 3ature|118244047',
            'AELLOW',
            'AHY2',
            'Ai Boy',
            'AI Angelina Jolie',
            'AI Chloe Grace Moretz',
            'AI Frontier Rev',
            'AI Natalie Portman',
            'Ai Porn Work',
            'AI Rachel McAdams',
            'Ai_emikoo',
            'AI_Omaga',
            'AI-TAKASHI-YA',
            'AiASAG',
            'AIBUNNY',
            'aiEgg',
            'AiFantasy',
            'aijuicer',
            'AIPotions',
            'AIShowMe',
            'AItono',
            'AIusagichan',
            'AIWaifuClub',
            'A[Ii]WaifuDXD',
            'AI小松鸟',
            'Akatsuki Ichika World',
            'Allenby',
            'AlwaysOlder',
            'Amakawa is reflecting',
            'AndestanVita042|117458084',
            'Anilvl',
            'AnimeParadise',
            'Anipai|ANIPAI',
            'Ankake Nameko|餡掛けなめこ',
            'Anor Londo',
            'Anto-kun',
            'ARD [\\s\\S]+ \\(Patreon\\)|\\[ARD\\]',
            'ArfX',
            'ArimaAgamiAI',
            'Artifical Art',
            'artriako',
            'ASDFG-did-lover',
            'Asphyxia',
            'atorieHJ',
            'Axiah',
            'Ayaaaaa|91528372',
            'Azusa_Yui',
            'AzzAI',
            'BaldSensei',
            'Balecxi',
            'BBstaff|BBStaff',
            'Benj17',
            'BGM ∞',
            'Bigornox',
            'Black Miracle',
            'BlackedNeeko',
            'Blavker|13881681',
            'bleachmama',
            'Blue Forest',
            'BMS07',
            'Boobacious',
            'Boryuka',
            'BribristleBowie',
            'BubbleTeeXL',
            'ByTheBroken1',
            'CCCraftA[Ii]|CC Craft A[Ii]',
            'Chickenbeautiful',
            'chiko_',
            'Chocopizza|ChocoPizza',
            'ChurnVeil',
            'Cidrex',
            'circle_ueponzu',
            'Civitai',
            'cMonster',
            'CodeMistake',
            'Coldenic',
            'Comboappofrice',
            'CometAzur',
            'Coolsummer',
            'corntoss',
            '^Crank',
            'Creamy AI',
            'Custom Firingu X',
            'Cyber-Wifu',
            'DarkFallenAngel',
            'Dartzai',
            'DeepMole',
            'DiaseePauwel',
            'Digital Waifu Gallery',
            'Dino@Top|41090148',
            'DreamcoreArt',
            'DomSweMale',
            'Donbe',
            'DozyMoth',
            'Dsd Adw',
            'Ecchi Eden',
            '^Eden ',
            'EKYNOXE',
            'Emi Doodlez',
            'EroartAI',
            'Ero[Mm]omo [\\s\\S]+ \\(Patreon\\)',
            'EroSketch',
            'Ezbreeze',
            'Floox508',
            'Freadeeb_TnT',
            'FryTime',
            'Futagenn',
            'FuyuBloom',
            'Generic_senpAI',
            'Genova pixiv',
            'Geo[ \\-]san',
            'Gettan',
            'GizGizmGimo',
            'Good Morning-sama',
            'Gragas743|gragas743',
            'GreekoAI',
            'GREENHEART',
            'H Jam',
            'Hajily',
            'Hammiai',
            'harajiro_butakimchi',
            'Hell[Tt]o[Yy]ou',
            'Hentai Hideout',
            'HentAI_Rtist',
            'HikaruAI',
            'hirosaTochisato',
            'HiStoryIa',
            'HONGCHA',
            'Hot Finger Pepper',
            'Howsir',
            'hstorytaimu',
            'Hurry-Workshop/Anivoice',
            'illyFurina',
            '[Ii]lululover',
            'IronAIArt',
            'ItzzMendo',
            'JessieAI',
            'JJNKAI',
            'JoeinPixels',
            'Jonn Cinabonn Jovi',
            'Jukujo Kami no Kuroana|熟女神の黒穴',
            'Kaiysx',
            'KALA AI NSFW',
            'KalistaFunz',
            'Kangaroo [\\s\\S]+ \\(Patreon\\)|カンガルー/ Kangaroo',
            'KatKirara',
            'KawaGawa|117534671',
            'keoly',
            'Kichiku-Sensei',
            'Kinzuia_chan',
            'KisenAI',
            'KM KingMaster|KM \\| KingMaster',
            'Kord A[Ii]',
            'Koryax',
            'Laino Airt',
            'Lam Vex',
            'LAMON',
            'LewdLilith',
            'LigmaSugmadi',
            'LimbusCompany',
            'Liname',
            'LiveFrog|FrogAI',
            'Lord of Waifus',
            'Lovehuwu|LoveHUwU',
            'LovelyZen',
            '[Ll]ovenight',
            'LustBild',
            'Lusty ?Nymphi',
            'LuxaArtdios',
            'Ly117',
            'MacArooN',
            'Machina Ai',
            'Magiskuwa',
            'markinson|106442227',
            'Märchen',
            'MaxMusclerlc',
            'Meowu laha',
            'MessingwithAI',
            'Mesubutagoya|雌豚小屋',
            'Mikayori',
            '^miko ',
            'Milf_kun',
            'MKyBUSH',
            '^MML ',
            'MMLOVE|91707537',
            'mnemosynekoto|Mnemosynekoto',
            'mochimochiya',
            'Mofulyen',
            'Mogu-Tyan',
            'Moke P@treon',
            'MOKIIIMOKIII',
            'Momoyashiki Akari',
            'Moon Petal',
            'MountCre',
            'mpena24',
            'MrTeardrop',
            'Mugi \\| むぎ',
            'Murata_san_FANBOX',
            'Myanu',
            'Nakanaka nana',
            'Nakatori',
            'Nameless King',
            'Nankoai',
            'Nasty|18386645',
            'Necromancer893',
            'Nekohouse ID',
            'nelshot',
            'Neroshiboshi',
            'Netorare-san',
            'niauno|16691530',
            'Nixny',
            'NO ONE pixiv',
            'Noffa',
            'NosferartIA',
            'NSFW Art137',
            'NSFWreigan',
            'NSN Studio',
            'NTRCookie',
            'ntrzelda',
            '[Nn]yx[Ww]orks',
            'Ogurifo',
            'OIGrizzle',
            'Okazai Art',
            'Oniha-|\\[[Oo]niha\\]',
            'ooqwqqaq',
            'OpisVore',
            'osanpomichi',
            'Panic america',
            'Pirate Wind Cat',
            'PixelNinjaArt',
            'Poggerrogger',
            'Ponponmaru',
            'PriestOfArt',
            'Primo Sensei',
            'ProGenArts',
            'PsyopsAI',
            'Purpleh31',
            'QAQ2\\.0|102102635',
            'Ramen-chan',
            'RandoAI',
            'Rasha125',
            'RazorThreat',
            'Realistic AI works',
            'Redilus',
            '^rei ',
            'ReiNa',
            'ReverendGreatLove',
            'RinkoRen',
            'Rino-mii_Noa',
            'Rqxy|6156788',
            'RUIMA',
            'Rule34Lab',
            'Ryan4s\\(93340616\\)',
            '^SANARIA [\\s\\S]+ \\(Patreon\\)',
            '^Sayaka [\\s\\S]+ \\(Patreon\\)|\\[Sayaka\\]',
            'Sbookner',
            'Scriptorium',
            'SEN-HWA',
            'Sephiaton',
            'SharinelAI',
            'Sheldon NTR',
            'Shinimono|しにもの',
            'Shione\'s works',
            'Shirobako88',
            'SInNA',
            'SkyPassion',
            'SlutCentralAI',
            'Smol NTR',
            'Sodalord',
            'solomon10',
            'Spairk1313',
            'SpasiboAI',
            'Squeeshy',
            'Starsay',
            'StasisBBC',
            '[Ss]tefan',
            'stella (?:- |)\\[NSFW\\]',
            '^Stormy',
            'StrayRevy',
            'Strelitzia',
            'subcharalove',
            's\\.h\\.t|11751692',
            'tabakowayame',
            'Tamagochiiii',
            'Taroberry',
            'Taugust',
            'terusa [\\s\\S]+ \\(Patreon\\)',
            'Thebardspirit',
            'TheMaker___',
            'Tiger87|タイガー87',
            'TipperGoreWasRight',
            'Tkz\\(116616648\\)',
            'tonkotsu_soup|Tonkotsu Soup',
            '^Toratora |\\[Toratora\\]',
            'TorogaoUni',
            'TrogiAi',
            'TsarAi',
            'TSM2330',
            'Tsubaki [\\s\\S]+ \\(Patreon\\)',
            'Tsukinoo',
            'ufiaw',
            '[Uu]nifans',
            'UnityNay',
            '^unreal ',
            'userzon',
            'Vanitas_AI',
            'Velurieve',
            'VertiloAI',
            'VirusB90',
            'Wagamama\\!\\!\\!',
            'Waifu Perfection AI',
            'WaifuArchitect',
            'WaifuInvoker',
            'WaifuLover',
            'Wardens',
            'WarOfFree98',
            'warofree',
            'weeb2weeb',
            'WienerGens',
            'wwwww2',
            'xyxonrh',
            'yagaminomori|ヤガミノ杜|\\(emiya\\)',
            'YakeArt',
            'yanai_hide',
            'YashugAI',
            'Yeeting',
            'Yokuto',
            'YORU NEKO',
            '(?:^| )yoshi ',
            '^Yukina |Yukina [\\s\\S]+ \\(Patreon\\)',
            'Yukino A[Ii]',
            '^yuyu ',
            'Zcqrlet',
            'zipzip|Zipzip',
            '\\[11_22\\]',
            '\\[aHero\\]',
            '\\[AIbro\\]',
            '\\[AIlya\\]',
            '\\[Akihime\\]',
            '\\[[bB]onno\\]',
            '\\[coqiaku\\]',
            '\\[Daisy\\]',
            '\\[Darkmagic\\]',
            '\\[Feather\\]',
            '\\[Fraia\\]',
            '\\[Girlstar\\]',
            '\\[Himeno\\]',
            '\\[HYC\\]',
            '\\[Kanuck\\]',
            '\\[Komachan\\]',
            '\\[(?:Komagome|こまごめピペット)\\]',
            '\\[ManAI\\]',
            '\\[(?:Milk Paradise|みるくパラダイス)\\]',
            '\\[minakaze\\]',
            '\\[Miyu\\]',
            '\\[Meow\\]',
            '\\[myuto\\]',
            '\\[NONOSAN\\]',
            '\\[noroj\\]',
            '\\[NT00 Fans\' Fan-Created Works\\]',
            '\\[Nyc3e\\]',
            '\\[Okreet\\]',
            '\\[OTA\\]',
            '\\[POGO\\]',
            '\\[Potions\\]',
            '\\[PS-AI\\]',
            '\\[Remon\\]',
            '\\[Ryx\\]',
            '\\[Setsuna\\]',
            '\\[Sukesuke\\]',
            '\\[yang\\]',
            '\\[Zuki\\]',
            '\\[ドゥドゥ\\]',
            '\\[ぱにぱに\\]',
            '\\([Aa]lbatross\\)',
            '\\(HentaiLove\\)',
            '\\(MULLON\\)',
            '\\(Nanami\\)',
            '\\(Patreon\\) Chizuru - ',
            '\\(Sylveria\\)',
            '\\(week2343\\)',
            '\\(紫月\\)',
            '^【AI自制】',
            '【黄色固体胶（zzzzz\\）】',
            'あま原屋',
            'えむすたでぃお',
            'エロエロ研究会',
            'お姉さん 【(?:GOLD|SILVER)】',
            'かたい棒 Hard Stick',
            '^かーむ ',
            'ゴールシックス',
            'こまごめピペット',
            'シコリの森',
            'じゃがいもホクホク北海道',
            'ぬきのすけ',
            'めろんアイスちゃん寝る',
            'ラブリークラフト',
            'わさびまぐろ',
            '阿古りむ|AKoRimu Art',
            '安托哦_Antuoo|41145678',
            '淫乱マッスル',
            '梅洞てんぷりゃー',
            '絵師たか',
            '鬼畜小次郎',
            '鬼见愁',
            '狗百代',
            '狗飯D|65800736',
            '小涩猫猫Nekolock \\(108435514\\)',
            '墨迹',
            '咕哒guda',
            '羞恥工房',
            '私立 ななつ星中',
            '田边重工',
            '他力本願寺',
            '泽拉图',
            '天空之上|51354050',
            '名無しのあに◯ん民',
            '右向カレイ|86707199',
            '油炸小肥龙',
            '夜あくび小隊',
            '丶黑谷雨泽',
            'futanari',
            'collection'
        ]
        regtitle = RegExp(arrtitle.join('|'));

        elements = document.querySelectorAll('table.itg.glte > tbody > tr');
        for (element of elements){
            if (regtitle.test(element.querySelector('div.glink').innerText)){
                element.style.display = 'none';
            }
        }
    }
    popUp = function (URL, w, h){
        var arrMatch, element;
        arrMatch = URL.match(/gid=(\d+)&t=/);
        if (arrMatch){
            element = document.getElementById('posted_' + arrMatch[1]);
            if (element){
                navigator.clipboard.writeText(element.innerHTML);
            }
        }
        return(false);
    }
} else if ((/^https?:\/\/e-hentai\.org\/g\/\d+\/[0-9a-f]+\/(?:\?p=\d+)?$/).test(document.URL)){
    (function() {
        var element, strH;
        element = document.querySelector('div.gm');
        strH = '20px';
        function ClickElement(){
            if (element.style.overflow == 'hidden'){
                element.style.height = 'auto';
                element.style.overflow = 'visible';
            } else {
                element.style.height = strH;
                element.style.overflow = 'hidden';
            }
        }
        element.style.height = strH;
        element.style.overflow = 'hidden';
        element.addEventListener('click', ClickElement, false);
    })();
} else if ((/^https?:\/\/e-hentai\.org\/s\/[0-9a-f]+\/\d+-\d+(?:\?nl=\d+-\d+)?$/).test(document.URL)){
    (function() {
        var strURL, arrMatch, strFileName;
        function PasteFileName(){
            navigator.clipboard.writeText(strFileName);
        }
        strURL = document.URL;
        arrMatch = strURL.replace(/\?[\s\S]+$/, '').match(/(\d+)-(\d+)$/);
        if (arrMatch){
            strFileName = arrMatch[1] + '-' + ('0000' + arrMatch[2]).slice(document.querySelector('#i2 > div.sn > div > span:nth-child(2)').innerHTML.length * -1);
            document.querySelector("#img").addEventListener('contextmenu', PasteFileName, false);
            document.querySelector("#i6").addEventListener('contextmenu', PasteFileName, false);
        }
    })();
}
